version: '2'
services:
  web:
    build: .
    volumes:
      - .:/var/www/vendas
    ports:
      - "3000:3000"
    command: 'bundle exec rails s -b 0.0.0.0'
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
