production:
  client_panel_url: http://localhost:3002
  products_url: http://localhost:3001/api
  send_order: /api/orders
development:
  client_panel_url: http://localhost:3002
  products_url: http://localhost:3001/api
  send_order: /api/orders
test:
  client_panel_url: http://localhost:3002
  products_url: http://localhost:3001/api
  send_order: /api/orders
