production:
  client_panel_url: http://paineldocliente.locaweb.com
  products_url: http://localhost:3001/api
  send_order: /api/order
development:
  client_panel_url: http://paineldocliente.locaweb.com
  products_url: http://localhost:3001/api
  send_order: /api/order
test:
  client_panel_url: http://paineldocliente.fake.com.br
  products_url: http://localhost:3001/api
  send_order: /api/order
